### ISSUE TITLE
badfish container can't talk to iDRACs without --dns

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/JetSki#108]
I'm using Fedora 33 and jetski needs to add podman option --dns=10.5.30.160 for podman to work.  i.e.
```
[bengland@fedora ansible-ipi-install]$ podman run --dns=10.5.30.160 -it --rm docker.io/quads/badfish -u quads -p rdu2@893 -i config/idrac_interfaces.yml -H mgmt-f20-h25-000-r640.rdu2.scalelab.redhat.com --check-boot --verbose 
- DEBUG    - Systems service: /redfish/v1/Systems/System.Embedded.1.
- DEBUG    - Managers service: /redfish/v1/Managers/iDRAC.Embedded.1.
- DEBUG    - Getting bios boot mode.
- DEBUG    - Getting BIOS attribute.
- WARNING  - Current boot order is set to: director.
```
That's because /etc/resolv.conf now points to:
```
nameserver 127.0.0.53
options edns0 trust-ad
search redhat.com lan1
```
Which apparently doesn't work for the podman container or is not visible to it.   One way to work around this is to edit in a red hat DNS server into /etc/resolv.conf (actually a softlink to something else now), and then pass option to badfish: "-v /etc/resolv.conf:/etc/resolv.conf", which makes this DNS server visible inside podman container.   There is no one place where I can patch things to make it work this way in JetSki (do grep -r podman .).

I guess I'll build a RHEL8 VM somewhere inside redhat and run JetSki from there.

**Comment by smalleni** [comment]
@bengland2 For now can you add 10.11.5.19 to your /etc/resolv.conf and re-kick jetski. Thanks!

**Comment by bengland2** [comment]
yeah that doesn't work because podman containers don't see that.    To make that work you'd have to add "-v /etc/resolv.conf:/etc/resolv.conf" as a podman option.   I've worked around it, there aren't many places in JetSki to patch for "podman run" at least, we'll see if this is good enough.   This was discussed in

https://github.com/redhat-performance/badfish/issues/140

**Comment by bengland2** [comment]
Here's what I wound up patching, so far so good...

http://perf1.perf.lab.eng.bos.redhat.com/pub/bengland/tmp/ms-etcd/logs/deploy.ansible-ipi-install.2021-02-16-15-26/git-diff.log
