### ISSUE TITLE
Containerize JetSki

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/JetSki#12]
While we use containers at various places in the code like running badfish commands/hammercli commands, we should containerize JetSki so that users have a consistent deployment experience regardless of what OS they are running JetSki from.

**Comment by smalleni** [comment]
@dustinblack thoughts?

**Comment by dustinblack** [comment]
This would take the simplicity for the end user a step further, and would obfuscate the somewhat confusing nature of the of ansible roles and the upstream relationship. Definitely worthwhile.
