### ISSUE TITLE
RH shared labs IPI installer fails due to 'dell_nodes' is undefined

### ISSUE THREAD

**Issue by akiselev1** [redhat-performance/JetSki#145]
I tried to follow Ansible-IPI Deployment Method  from https://docs.google.com/document/d/1hl2qVWyRjqhKT3ZR5Q2xn9Ip1DLShanxQcnp11Zf1tw/edit#heading=h.6fjg6ko1c2cj

ansible-playbook -i inventory/shared_labs/hosts playbook-rh-shared-labs.yml
fails at 

TASK [shared-labs-prep : Create temp directory for badfish] *******************************************************************************************************************************
Monday 17 May 2021  00:57:48 +0000 (0:00:01.539)       0:00:10.250 ************ 
fatal: [f32-h13-000-r640.rdu2.scalelab.redhat.com]: FAILED! => {"msg": "The conditional check 'dell_nodes | length > 0' failed. The error was: error while evaluating conditional (dell_nodes | length > 0): 'dell_nodes' is undefined\n\nThe error appears to be in '/root/JetSki/ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml': line 22, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: Create temp directory for badfish\n      ^ here\n"}

**Comment by smalleni** [comment]
> I tried to follow Ansible-IPI Deployment Method from https://docs.google.com/document/d/1hl2qVWyRjqhKT3ZR5Q2xn9Ip1DLShanxQcnp11Zf1tw/edit#heading=h.6fjg6ko1c2cj
> 
> ansible-playbook -i inventory/shared_labs/hosts playbook-rh-shared-labs.yml
> fails at
> 
> TASK [shared-labs-prep : Create temp directory for badfish] *******************************************************************************************************************************
> Monday 17 May 2021 00:57:48 +0000 (0:00:01.539) 0:00:10.250 ************
> fatal: [f32-h13-000-r640.rdu2.scalelab.redhat.com]: FAILED! => {"msg": "The conditional check 'dell_nodes | length > 0' failed. The error was: error while evaluating conditional (dell_nodes | length > 0): 'dell_nodes' is undefined\n\nThe error appears to be in '/root/JetSki/ansible-ipi-install/roles/shared-labs-prep/tasks/main.yml': line 22, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n block:\n - name: Create temp directory for badfish\n ^ here\n"}

That playbook is no longer supported, Please instead use ` playbook-jetski.yml`.

**Comment by akiselev1** [comment]
Thank you @smalleni ! I think the above referenced document needs to be updated ASAP to keep lab users up to date.

**Comment by smalleni** [comment]
> Thank you @smalleni ! I think the above referenced document needs to be updated ASAP to keep lab users up to date.

Thanks for the feedback, I made a comment but I'm not still sure who is using this doc and who is pointing to this doc. It's only probably worth referring to it for UPI. I do not own the doc, so please feel free to make comments as you go on the doc as that will help other future users as well.

**Comment by akiselev1** [comment]
Will Foster pointed us to that document as the current scale lab procedure: https://projects.engineering.redhat.com/browse/SCALELAB-1029?focusedCommentId=3153569&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-3153569

**Comment by akiselev1** [comment]
I saw the document got updated. Thank you!
