### ISSUE TITLE
pull-secret is double-quoted

### ISSUE THREAD

**Issue by rvansa** [redhat-performance/JetSki#173]
The `Convert pullsecret to JSON` in `ansible-ipi-install/roles/set-deployment-fact/tasks.main` cause the pull secret defined as
```yaml
pullsecret: '{"auths": ... }'
```
to end up with one extra layer of quoting, failing the playbook when the pull-secret file is used on the provisioner.

**Comment by smalleni** [comment]
Please use pullsecret as is - without any quotes @rvansa and let me know how it goes

**Comment by rvansa** [comment]
@smalleni I have installed OCP now (disabling the conversion) but I perceive the pull-secret as an opaque string, therefore pasting it as such. Putting the JSON straight into YAML seems awkward.
Maybe a check if the `pullsecret` is string or object would satisfy any use case.

**Comment by smalleni** [comment]
Ack. I think we had to make that change with something related to exporting these `group_vars/all.yml` as environment variables for tools like jenkins. We used to require a '' before that?

I like your idea, do you mind sending a PR?

**Comment by rvansa** [comment]
Created https://github.com/redhat-performance/JetSki/pull/174
