### ISSUE TITLE
Handle R650 corner cases to discover pub_nic as made for R640

### ISSUE THREAD

**Issue by marceloamaral** [redhat-performance/JetSki#189]
I recently tried to deploy OCP on a set of mixed R640 and R650 node types in scale lab, however the deployment has failed for the R650 node type. More specifically, the error was:
```
fatal: [e27-h01-000-r650.rdu2.scalelab.redhat.com]: FAILED! => {"msg": "Unexpected templating type error occurred 
on ({{ lab_pub_nics + [ lab_vars['machine_types'][item.0][item.1]['pub_nic'][0] ]  }}): can only concatenate str 
(not \"list\") to str"}
```

Reviewing the code, I realized that there is a lot of logic for finding the public nic of the R640 and the logic for the R650 is missing. Maybe the R650 are new machines...

Therefore, we also need to handle the R650 corner cases as done for the R640 node type.

**Comment by mukrishn** [comment]
@marceloamaral thanks for bring this up, yesterday we included below dict to include r650 servers and I see it worked. 
```
      r650:
        pub_nic: eno12399np0
        prov_nic: ens1f1
```
We will include this in JetSki.
