### ISSUE TITLE
JetSki needs to wait after sending mutating commands to iDRAC

### ISSUE THREAD

**Issue by RobertKrawitz** [redhat-performance/JetSki#19]
After JetSki sends a mutating command to iDRAC it needs to wait for the command to succeed.
In particular, `--clear-jobs -f` (at least on a Dell 740xd) results in the following if one attempts to access it immediately:
```
mgmt-host.example.com: - ERROR    - internal error, 
- INFO     - None
- ERROR    - ComputerSystem's Members array is either empty or missing
- ERROR    - There was something wrong executing Badfish.
```
My manual workaround is to run `--check-boot` every 30 seconds or so until it succeeds.

Similarly, after sending a `-t foreman` or `-t director` command, it's necessary to wait until that command "takes" (which will be after the node reboots).

**Comment by bbenshab** [comment]
so during the last few days, I did all kinds of testing and from what I have seen BadFish API calls returns as a success but in reality, nothing really happened, not sure if this issue only applicable for dell servers.
I took a different approach to this, and instead of using RedFish/Badfish I used racadm to speak directly to the BMC, and the deployment completed successfully with JetSki.

**Comment by smalleni** [comment]
@bbenshab that hasn't been the experience for me in Scale lab. We need to figure out a way to make JetSki work for ALIAS OOTB. Between what @RobertKrawitz commented and what you found, would one of you be willing to submit a PR?

Also, just for the record, the boot order should have been set when the allocation is handed down to you from lab admins/automation.

@grafuls quick question, is badfish being used in the ALIAS lab?  Multiple people are reporting issues with using badfish in ALIAS (doesn't apply to scale lab).

**Comment by RobertKrawitz** [comment]
Badfish does work in the alias lab, just with the caveats I mentioned above.  But if racadm is more reliable, gopherit.

Don't rely on the order provided by lab administration.  One might want to use JetSki to reinstall a cluster, in which case the boot order will be different.

**Comment by ashishkamra** [comment]
@abondvt89 told me that scale lab does not have Dell 740xd machines so could this be specific to the 740xd machines in alias - can someone check if they are running the latest BIOS firmware released by Dell?

**Comment by smalleni** [comment]
@ashishkamra This should be harmless even when running against other types of machines. It's simply a wait..

**Comment by ashishkamra** [comment]
Sure, worth trying it out.

**Comment by grafuls** [comment]
> @grafuls quick question, is badfish being used in the ALIAS lab? Multiple people are reporting issues with using badfish in ALIAS (doesn't apply to scale lab).

It is being used in ALIAS and has been adapted to fit the requirements there. What are the issues?

**Comment by RobertKrawitz** [comment]
The most serious issue is that after calling `--clear-jobs -f`, iDRAC doesn't respond successfully to any further commands for several minutes, with the error message as displayed on the OP.  However, the command returns a status of 0, so any automation that relies on the return value will incorrectly think that the command in question (e. g. setting the boot order, powering on/off the node, etc) has succeeded when in fact it has not.

I've also seen cases where sending the same command multiple times results in iDRAC's not responding "correctly" to the commands other than the first.  For example, repeated attempts to set director boot order result in that not happening.  I don't have a clear record of this, however, and it may simply be due to not having waited long enough for the command to succeed.  Changing the boot order requires a reboot, and that can take 5 minutes on a 740xd.

**Comment by smalleni** [comment]
> > @grafuls quick question, is badfish being used in the ALIAS lab? Multiple people are reporting issues with using badfish in ALIAS (doesn't apply to scale lab).
> 
> It is being used in ALIAS and has been adapted to fit the requirements there. What are the issues?

@grafuls , Does badfish return a non-zero error code when an operation fails? In our case it returns success even if --check-boot fails.
