### ISSUE TITLE
Add Bring your own Lab

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/JetSki#31]
JetSki is tailored to run in Scale and ALIAS labs. But as long as a user provides his/her own inventory file (ocpinv.json), we should support other labs as we..

**Comment by ashishkamra** [comment]
@smalleni I would like to revive this issue specifically targeting the IBM cloud BM environment as another target for jetski based OCP deployment.

**Comment by smalleni** [comment]
@ashishkamra Given your team has the most experience with OCP deployments in IBM cloud, would someone be willing to steer this for IBM cloud?

**Comment by ashishkamra** [comment]
@ebattat can potentially do it. But he is also very busy with building the automation to get us to do CNV workloads performance work for OCP 4.9. Let me check if anyone else can pick it up.

**Comment by ashishkamra** [comment]
Given Alex's work in Jetlag for the IBM cloud - https://github.com/redhat-performance/jetlag/blob/main/docs/deploy-bm-ibmcloud.md#deploy-a-bare-metal-cluster-on-ibmcloud-via-jetlag-quickstart - at least my requirement is satisfied. Thanks @akrzos

**Comment by ashishkamra** [comment]
This issue can be closed.
