### ISSUE TITLE
Add dns entries for all hosts from the inventory file

### ISSUE THREAD

**Issue by mkarg75** [redhat-performance/JetSki#32]
As of now, JetSki only creates dns entries for the nodes that are being used during the installation. For later scale outs it's required to parse the inventory file again and create the remaining dns entries for dnsmasq. It'd be good if that could be done during the installation already, possible with a switch that defaults to off if that is not a common usecase.

**Comment by smalleni** [comment]
@jaredoconnell Would you like to work on this?

**Comment by jaredoconnell** [comment]
@smalleni That seems like a good task once I finish my current task.
