### ISSUE TITLE
Fix chrony issues

### ISSUE THREAD

**Issue by mulbc** [redhat-performance/JetSki#36]
After the install with ipi my time was not able to sync. Apparently one needs to use the interal NTP servers `clock.corp.redhat.com`

You can check if time is syncronized with `chronyc tracking`

After deployment this can be done to fix this:
`echo "pool clock.corp.redhat.com iburst" | sudo tee -a /etc/chrony.conf ;sudo systemctl restart chronyd`

**Comment by e-minguez** [comment]
Just in case, you can specify a list of ntp servers in the inventory file. The upstream repo example inventory file lines are https://github.com/redhat-performance/JetSki/blob/master/ansible-ipi-install/inventory/jetski/hosts#L55-L56 and in your fork it seems it is already there as well https://github.com/redhat-performance/JetSki/blob/master/ansible-ipi-install/inventory/jetski/hosts#L55-L56

**Comment by mulbc** [comment]
Since JetSki is envisioned as a ready to go fork of baremetal-deploy I expected these things to be set as default (because without this change the clocks are not syncronized)

**Comment by mulbc** [comment]
If you don't plan to uncomment this (and make chrony work by default), I can close this issue... Is that what you want?

**Comment by smalleni** [comment]
@e-minguez Is there a reason you have the clock_servers var commented out by default? How does NTP occur for etcd etc if that is commented out?

**Comment by e-minguez** [comment]
> @e-minguez Is there a reason you have the clock_servers var commented out by default? How does NTP occur for etcd etc if that is commented out?

Because you need to provide the ones that you want :) Usually customers have their own internal clock server so there is no point to have one by default.

**Comment by smalleni** [comment]
> > @e-minguez Is there a reason you have the clock_servers var commented out by default? How does NTP occur for etcd etc if that is commented out?
> 
> Because you need to provide the ones that you want :) Usually customers have their own internal clock server so there is no point to have one by default.

Well, I meant the playbook works and we get a successful install without providing any :) So wasn't sure how the clustered services like etcd would form a quorum

**Comment by mulbc** [comment]
> Usually customers have their own internal clock server so there is no point to have one by default.

The way I understand the JetSki repo is that it is a modified version of openshift-kni/baremetal-deploy explicitly set for the scale lab. In the scale lab, you will only ever be able to use the Red Hat NTP servers... so IMO these should be uncommented in the JetSki repo.

**Comment by smalleni** [comment]
Agreed, going to fix the default inventory for JetSki
