### ISSUE TITLE
Add an option in Jetski to build a cluster with a single node master

### ISSUE THREAD

**Issue by ashishkamra** [redhat-performance/JetSki#94]
Many OpenShift cluster deployments within perf dept are used for testing data plane workloads on one or two worker nodes. To build a two worker node cluster, a total of 6 machines need to be requested (3 Masters, 2 workers, 1 provisioning/admin/jump). The idea behind this enhancement is to bring down such requirement to 4 machines by building an OpenShift cluster with a single node master - as described by @jmencak in his notes - https://docs.google.com/document/d/1_T-ZBAz4yoU5B_EI2e70xDrGXEM-4gqWqnQYzvq471I/edit. This will help improve the alias lab utilization which is running at > 90% capacity due to increased demands for building OpenShift clusters.

**Comment by smalleni** [comment]
Please use jetlag to do this using assisted installer (SNO): https://github.com/redhat-performance/jetlag
